### ISSUE TITLE
-[NSNull objectForKeyedSubscript:]: unrecognized selector sent to instance 0x195fede70

### ISSUE THREAD

**Issue by souhl** [comyarzaheri/CZWeatherKit#16] opened 2015-05-18 11:12 UTC
We got a crash in 
   -[CZOpenWeatherMapService parseCurrentConditionsFromJSON:] (in MyWeatherCenter) (CZOpenWeatherMapService.m:146)

What is the best way to handle this? Is it enough to check JSON for Null value in parseCurrentConditionsFromJSON?

Thanks
Sascha

**Comment by comyarzaheri** [comment] 2015-05-19 02:36
Could you provide some information on how to recreate this? What city/coordinate/etc are you getting data for? Are you using an API key? A small code sample would help diagnose this.

I believe I know what the issue is, so I'll go ahead and mark this as a bug.

**Comment by souhl** [comment] 2015-05-19 12:17
Yes, I am using an API Key. And this doesn't happen always. It just happened a few times now.

CZWeatherRequest *request = [CZWeatherRequest requestWithType:CZCurrentConditionsRequestType];
    request.location = [CZWeatherLocation locationWithCLLocationCoordinate2D:place.coordinate ];
    request.service = [CZOpenWeatherMapService serviceWithKey:@"32e0733fa21924e6df66f8ddfcXXXXX"];
    LogDebug(@"WEATHERREQUEST STARTED");
    
    if (timeOut == NULL) {
        
        timeOut = [NSTimer scheduledTimerWithTimeInterval: 3
                                                   target: self
                                                 selector: @selector(cancelURLConnection:)
                                                 userInfo: nil
                                                  repeats: NO];
        //[timeOut retain];
    }

    [request performRequestWithHandler:^(id data, NSError *error) {
        if (data) {
            [timeOut invalidate];
            LogDebug(@"WEATHERREQUEST DATA RETRIEVED");

**Comment by comyarzaheri** [comment] 2015-05-19 19:55
What's value of `place.coordinate` when it fails?

I'm guessing OpenWeatherMap's response contains `"main": null` in its response even when it doesn't have data for the given coordinate. If you see [line 145](https://github.com/comyarzaheri/CZWeatherKit/blob/master/CZWeatherKit/Service/CZOpenWeatherMapService.m#L145) in OpenWeatherMapService.m then it makes sense why this is failing; `JSON[@"main"]` is returning `NSNull` and then we're trying to use the `NSNull` as a dictionary. I'll read up on their API to make sure this is what's happening.

**Comment by souhl** [comment] 2015-05-21 12:45
I added a check with CLLocationCoordinate2DIsValid and will test again.

**Comment by comyarzaheri** [comment] 2015-05-29 00:52
I'm currently working on an update to fix this issue. Just wanted to let you know.

**Comment by souhl** [comment] 2015-06-01 08:32
Great! Thanks

**Comment by comyarzaheri** [comment] 2015-06-02 04:51
Alright, I think this is resolved in the new release. I'll go ahead and close this issue, but please open it again if you find any issues. Thanks.

**Closed by comyarzaheri** 2015-06-02 04:51 UTC
Labels: bug
